### PR TITLE
Fix for OS X & non-LSB

### PR DESCRIPTION
**Pull request by kamil4521**
Hello,

I make fix for OS X & non-LSB distributions. I tested on OS X Yosemite.

### CODE REVIEW

**Comment by kamil4521** [comment]
Changes in the library commander.

I set the old version of the library. Now all the tests pass.

**Comment by 92bondstreet** [comment]
Thanks. I'll take time to merge it and publish to npm registry.

**Comment by kamil4521** [comment]
Hello, I added support RedHat init.d scripts format.

**Comment by 92bondstreet** [comment]
Thanks. Published on npmjs.

**Pull request merged**
